sudo: false
language: node_js
node_js:
    - stable
    - "0.12"
before_install:
    - npm install
    - cd generatorTests
install:
    - npm install
    - npm install -g mocha
    - npm install -g gulp
script: 
    - mocha